Repository ISISComputingGroup/system_tests, pull requests merged in 2020-07, with the labels that each got.

#53 Use raw string
  test_genie_python_dae.py
Labels: size/XS

#54 Initial alert system tests
  test_genie_python_using_simple.py
Labels: size/M

#55 Fixed broken test
  test_genie_python_using_simple.py
Labels: size/XS

#56 Fix final assert
  test_genie_python_using_simple.py
Labels: size/XS

#57 Add system test for g.alerts.send()
  test_genie_python_using_simple.py
Labels: size/S

#58 increased server timeout
  utilities/utilities.py
Labels: size/XS

#59 Fix deletion retries
  run_tests.py
Labels: size/XS

#60 Fix test
  test_genie_python_using_simple.py
Labels: size/XS

#61 fixed typo
  utilities/utilities.py
Labels: size/XS
