Repository ISISComputingGroup/system_tests, pull requests merged in 2020-02, with the labels that each got.

#34 Ticket5109 run individual tests
  README.md
  run_tests.bat
  run_tests.py
Labels: size/L

#32 Ticket4992 raise invalid period exception
  test_genie_python_dae.py
  utilities/utilities.py
Labels: size/M

#33 Enable running of debug build tests
  Jenkinsfile
Labels: size/XS
