Repository ISISComputingGroup/system_tests, pull requests merged in 2020-06, with the labels that each got.

#43 Basic test for alarm logging array
  configs/configurations/rcptt_simple/blocks.xml
  test_genie_python_dae.py
Labels: size/M

#44 Re-enable tests
  test_genie_python_dae.py
Labels: size/M

#46 Fix test+after genie changes
  test_genie_python_dae.py
  test_genie_python_using_simple.py
Labels: size/S

#48 Add sleep between file read retries
  test_genie_python_dae.py
Labels: size/XS

#49 Check exit codes
  run_tests.bat
Labels: size/S

#50 Added check for docker on tear down
  test_datastreaming.py
Labels: size/XS

#51 Ticket 5483: Fix DAE block test
  test_genie_python_dae.py
  utilities/utilities.py
Labels: size/L
