Repository ISISComputingGroup/system_tests, pull requests merged in 2022-09, with the labels that each got.

#92 Ticket7291
  configs/configurations/test_restart_ioc_when_pv_in_alarm/blocks.xml
  configs/configurations/test_restart_ioc_when_pv_in_alarm/components.xml
  configs/configurations/test_restart_ioc_when_pv_in_alarm/groups.xml
  configs/configurations/test_restart_ioc_when_pv_in_alarm/iocs.xml
  configs/configurations/test_restart_ioc_when_pv_in_alarm/meta.xml
  test_restart_ioc_when_pv_in_alarm.py
Labels: size/M

#93 Fix plotting tests for new plotting code
  test_plotting.py
Labels: size/S

#95 Add clearer dev instructions
  README.md
Labels: size/XS

#94 Add exception for importing private packages
  test_genie_python_common_imports.py
Labels: size/XS

#89 Tests for do_sans do_trans instrument scripts
  configs/configurations/instrument_scripts_larmor/blocks.xml
  configs/configurations/instrument_scripts_larmor/components.xml
  configs/configurations/instrument_scripts_larmor/groups.xml
  configs/configurations/instrument_scripts_larmor/iocs.xml
  configs/configurations/instrument_scripts_larmor/meta.xml
  configs/configurations/instrument_scripts_loq/blocks.xml
  configs/configurations/instrument_scripts_loq/components.xml
  configs/configurations/instrument_scripts_loq/groups.xml
  configs/configurations/instrument_scripts_loq/iocs.xml
  configs/configurations/instrument_scripts_loq/meta.xml
  configs/configurations/instrument_scripts_sans2d/blocks.xml
  configs/configurations/instrument_scripts_sans2d/components.xml
  configs/configurations/instrument_scripts_sans2d/groups.xml
  configs/configurations/instrument_scripts_sans2d/iocs.xml
  configs/configurations/instrument_scripts_sans2d/meta.xml
  configs/configurations/instrument_scripts_zoom/blocks.xml
  configs/configurations/instrument_scripts_zoom/components.xml
  configs/configurations/instrument_scripts_zoom/groups.xml
  configs/configurations/instrument_scripts_zoom/iocs.xml
  configs/configurations/instrument_scripts_zoom/meta.xml
  configs/tables/detector.dat
  configs/tables/detector35576_M4.dat
  configs/tables/detector8.dat
  configs/tables/detector_1det_1dae3card.dat
  configs/tables/detector_8mon_1dae3card_00.dat
  configs/tables/detector_gastubes_01.dat
  configs/tables/detector_monitors_only.dat
  configs/tables/detector_trans8.dat
  configs/tables/spec2det_130218.txt
  configs/tables/spec2det_280318_to_test_18_1.txt
  configs/tables/spectra35576_M4.dat
  configs/tables/spectra8.dat
  configs/tables/spectra_1To1.dat
  configs/tables/spectra_monitors_only.dat
  configs/tables/spectra_trans8.dat
  configs/tables/spectrum_8mon_1dae3card_00.dat
  configs/tables/spectrum_gastubes_01.dat
  configs/tables/wiring1det_event_200218.dat
  configs/tables/wiring1det_histogram_200218.dat
  configs/tables/wiring35576_M4.dat
  configs/tables/wiring8.dat
  configs/tables/wiring_8mon_1dae3card_00_hist.dat
  configs/tables/wiring_dae3_event.dat
  configs/tables/wiring_dae3_monitors_only.dat
  configs/tables/wiring_gastubes_01_event.dat
  configs/tables/wiring_trans8.dat
  run_tests.py
  test_blockserver.py
  test_instrument_scripts.py
  utilities/utilities.py
Labels: size/XXL
