Repository ISISComputingGroup/system_tests, pull requests merged in 2025-01, with the labels that each got.

#119 Fixes pyright system tests
  test_genie_python_using_simple.py
Labels: size/M

#120 add configobj to requirements.txt
  requirements.txt
Labels: size/XS

#122 add system test for checking that set_pv_value() with None as value d…
  test_genie_python_using_simple.py
Labels: size/S

#121 make genie python raise exceptions by default
  run_tests.py
Labels: size/XS

#105 Update README.md
  README.md
Labels: size/XS
